# Generated by Django 5.2 on 2025-04-30 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('app_type', models.CharField(choices=[('request', 'Request'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], max_length=20)),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
